; Version 1.5

; === Variables ===
[Variables]

; ===== Dimensions =====
CoverSize=200
CoverSizeHalf=(80)
SmallCoverSize=(#CoverSize#/2)
PlayerIconSize=(#SmallCoverSize#/2.5)
CoverOffset=0

; ===== Spacing =====
Padding=20
SmallCoverMargin=20
PlayerIconMargin=10
DecoIconMargin=-50

; ===== Colors =====

; == Dark ==

; Background
BGColor_Dark=0,0,0

; Accents
AccentColor_Dark=241,241,241
TextColor_Dark=241,241,241

; Progress Bar
ProgressBGColor_Dark=124, 119, 90

; == Light ==

; Background
BGColor_Light=241,241,241

; Accents
AccentColor_Light=21,21,21
TextColor_Light=21,21,21

; Progress Bar
ProgressBGColor_Light=48,48,48,50

; == Multi ==
AccentColor_Red = 199, 198, 157

; ===== Animation =====
HoverOffset=120
AnimationSpeed=5
AnimationSteps=60
AnimationDuration=50
EasingFactor=0.5
ReturnSpeedMultiplier=2

; ===== Typography =====
FontFace=Roboto
TitleFontSize=14
ArtistFontSize=14
TitleFontWeight=400
ArtistFontWeight=100
CharacterSpacing=1

; ===== Layout =====
; Corners
CornerRadius=27

; Progress Bar
ProgressBarHeight=3
ProgressBarRadius=2

; Positioning
InfoTextYOffset=40
ArtistTextYOffset=70
ProgressBarYOffset=10

; ===== Icons =====
DecoIconSize=25

; ===== Default Images =====
DefaultCover=#@#Images/NothingCover.png
DefaultPlayerIcon=#@#Icons/Spotify.png

; ===== Animation Timings =====
TintDuration=500
FadeSteps=10
FadeInterval=10
IconFadeSteps=10
IconFadeInterval=20

; Equalizer Settings
EqualizerBarWidth=5
EqualizerBarMaxHeight=15
EqualizerBarMinHeight=5
EqualizerBarSpacing=2
EqualizerBarCount=4
EqualizerBottomMargin=25
EqualizerLeftMargin=25
EqualizerSensitivity=2.5
EqualizerSmoothing=0.7


EqualizerCurrentColor=241,241,241,180 ; Default

LightBarColor=241,241,241
DarkBarColor=48,48,48

; === Circle Sizes ===
CircleSize=90



; === Menu Configuration ===
[Variables]
; Grid Layout
GridColumns=2
GridRows=4
ItemWidth=220
ItemHeight=280
ItemSpacing=20
GridStartX=20
GridStartY=80

; Categories (add your categories here)
Category1=Battery
Category2=Clock
Category3=Date
Category4=Insights
Category5=Monitor
Category6=Music
Category7=Photos
TotalCategories=7

; Paths
ImagePath=#@#Menu\Category\
SkinImagePath=#@#Menu\Skin_IMG\

; Communication
CurrentCategory=
CurrentSkinOption=1
TotalOptionsPerCategory=3

; Colors
MenuBG=27,28,29,240
AccentColor=192, 193, 152
TextColor=241,241,241
HoverColor=60,60,60,255
CornerRadius=27

; Animation
ScrollSpeed=280
AnimationSpeed=5
